import React, { forwardRef } from 'react';

const PrintPrescription = forwardRef(({ data }, ref) => {
  if (!data) return null;

  const { appointment, medicines, notes } = data;
  const patient = appointment?.patientId;
  const doctor = appointment?.doctorId;

  return (
    <div ref={ref} className="p-10 bg-white text-black font-sans max-w-3xl mx-auto">
      {/* HEADER: CLINIC & DOCTOR INFO */}
      <div className="flex justify-between items-start border-b-2 border-gray-800 pb-6 mb-6">
        <div>
           <h1 className="text-3xl font-bold uppercase tracking-wider text-blue-900">MediCare Clinic</h1>
           <p className="text-sm text-gray-600 mt-1">123 Health Street, Medical District</p>
           <p className="text-sm text-gray-600">Ph: (555) 123-4567</p>
        </div>
        <div className="text-right">
           <h2 className="text-xl font-bold text-gray-800"> {doctor?.name}</h2>
           <p className="text-sm text-gray-600 uppercase">{doctor?.specialization || 'General Physician'}</p>
           <p className="text-xs text-gray-500 mt-1">Reg No: 12345678</p>
        </div>
      </div>

      {/* PATIENT DETAILS */}
      <div className="bg-gray-50 p-4 rounded-lg border border-gray-200 flex justify-between items-center text-sm mb-8">
         <div>
            <span className="text-gray-500 font-bold uppercase mr-2">Patient Name:</span>
            <span className="font-semibold text-lg">{patient?.name}</span>
         </div>
         <div>
            <span className="text-gray-500 font-bold uppercase mr-2">Age/Sex:</span>
            <span>{patient?.age} Y / {patient?.gender}</span>
         </div>
         <div>
            <span className="text-gray-500 font-bold uppercase mr-2">Date:</span>
            <span>{new Date().toLocaleDateString()}</span>
         </div>
      </div>

      {/* RX SYMBOL */}
      <div className="mb-4">
         <span className="text-4xl font-serif italic font-bold text-gray-400">Rx</span>
      </div>

      {/* MEDICINES TABLE */}
      <table className="w-full mb-8 border-collapse">
        <thead>
          <tr className="border-b-2 border-gray-100 text-left">
            <th className="py-2 font-bold text-gray-700 w-5">#</th>
            <th className="py-2 font-bold text-gray-700">Medicine Name</th>
            <th className="py-2 font-bold text-gray-700">Dosage</th>
            <th className="py-2 font-bold text-gray-700">Frequency</th>
            <th className="py-2 font-bold text-gray-700">Duration</th>
            <th className="py-2 font-bold text-gray-700 text-right">Instructions</th>
          </tr>
        </thead>
        <tbody>
          {medicines.map((med, idx) => (
            <tr key={idx} className="border-b border-gray-100">
               <td className="py-3 text-gray-500">{idx + 1}</td>
               <td className="py-3 font-semibold text-gray-800">{med.name}</td>
               <td className="py-3">{med.dosage}</td>
               <td className="py-3">{med.frequency}</td>
               <td className="py-3">{med.duration}</td>
               <td className="py-3 text-right text-gray-600 italic">{med.instruction}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* NOTES / DIAGNOSIS */}
      {notes && (
        <div className="mb-12">
           <h3 className="font-bold text-gray-700 uppercase text-sm border-b border-gray-200 pb-1 mb-2">Clinical Notes / Diagnosis</h3>
           <p className="text-gray-800 whitespace-pre-wrap leading-relaxed">{notes}</p>
        </div>
      )}

      {/* FOOTER / SIGNATURE */}
      <div className="mt-20 flex justify-between items-end">
         <div className="text-xs text-gray-400">
            <p>Generated by MediCare System</p>
            <p>{new Date().toLocaleString()}</p>
         </div>
         <div className="text-center">
            {/* If you had a signature image, it would go here */}
            <div className="h-16"></div> 
            <div className="border-t border-gray-400 w-48 pt-2">
               <p className="font-bold text-gray-700">Dr. {doctor?.name}</p>
               <p className="text-xs text-gray-500">Signature</p>
            </div>
         </div>
      </div>
    </div>
  );
});

export default PrintPrescription;